controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    # velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    

# velocity_controller:
#   ros__parameters:
#     joints:
#     - shoulder_1_joint
#     - shoulder_2_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#     command_interfaces:
#       - velocity
#     state_interfaces:
#       - position
#       - velocity
joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    # write_op_modes:
    #   - joint_1
    #   - joint_2
    #   - joint_3
    #   - joint_4
    #   - joint_5
    #   - joint_6
    
    # interface_name: position

    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)


